model: tabpfn.TabPFNRegressor
random_state: 42
results_dir: results/evaluate/limesoda_tabpfn_evaluate

fixed_parameters:
  n_estimators: 1
  device: cpu
  random_state: 42
  use_pca: false
  n_pca_components: null
  feature_scaling: null
  standardize_targets: true
  standardize_targets_tabpfn: false

datasets:
  - dataset: B.204
    target: SOC_target
  - dataset: B.204
    target: pH_target
  - dataset: B.204
    target: Clay_target
  - dataset: BB.250
    target: SOC_target
  - dataset: BB.250
    target: pH_target
  - dataset: BB.250
    target: Clay_target
  - dataset: BB.30_1
    target: SOC_target
  - dataset: BB.30_1
    target: pH_target
  - dataset: BB.30_1
    target: Clay_target
  - dataset: BB.30_2
    target: SOC_target
  - dataset: BB.30_2
    target: pH_target
  - dataset: BB.30_2
    target: Clay_target
  - dataset: BB.51
    target: SOC_target
  - dataset: BB.51
    target: pH_target
  - dataset: BB.51
    target: Clay_target
  - dataset: BB.72
    target: SOC_target
  - dataset: BB.72
    target: pH_target
  - dataset: BB.72
    target: Clay_target
  - dataset: G.104
    target: SOC_target
  - dataset: G.104
    target: pH_target
  - dataset: G.104
    target: Clay_target
  - dataset: G.150
    target: SOC_target
  - dataset: G.150
    target: pH_target
  - dataset: G.150
    target: Clay_target
  - dataset: MG.112
    target: SOC_target
  - dataset: MG.112
    target: pH_target
  - dataset: MG.112
    target: Clay_target
  - dataset: MGS.101
    target: SOC_target
  - dataset: MGS.101
    target: pH_target
  - dataset: MGS.101
    target: Clay_target
  - dataset: MWP.36
    target: SOC_target
  - dataset: MWP.36
    target: pH_target
  - dataset: MWP.36
    target: Clay_target
  - dataset: NSW.52
    target: SOC_target
  - dataset: NSW.52
    target: pH_target
  - dataset: NSW.52
    target: Clay_target
  - dataset: PC.45
    target: SOC_target
  - dataset: PC.45
    target: pH_target
  - dataset: PC.45
    target: Clay_target
  - dataset: SC.50
    target: SOC_target
  - dataset: SC.50
    target: pH_target
  - dataset: SC.50
    target: Clay_target
  - dataset: SM.40
    target: SOC_target
  - dataset: SM.40
    target: pH_target
  - dataset: SM.40
    target: Clay_target
  - dataset: W.50
    target: SOC_target
  - dataset: W.50
    target: pH_target
  - dataset: W.50
    target: Clay_target

optimization:
  n_trials: 0
  sampler: TPE
  sampler_params:
    n_startup_trials: 20
    multivariate: true
  cv:
    outer_folds: 5
    inner_folds: 5

outer_train_strategies:
  agg_epochs_mean_ensemble:
    enabled: true
    k: 16
