# ---------------------------------------------------------------
#  T2G-Former on LimeSoDa
# ---------------------------------------------------------------
model: t2g_former.T2GFormerRegressor
random_state: 42
results_dir: results/limesoda_t2gformer_optimize

# -------------------- fixed (non-optimised) --------------------
fixed_parameters:
  epochs: 256
  use_early_stopping: true
  early_stopping_rounds: 16
  device: cuda        # change to "cpu" if you do not have a GPU
  random_state: 42
  token_bias: true
  prenormalization: false
  initialization: kaiming
  feature_scaling: robust
  standardize_targets: true


# ------------- hyper-parameter search space -------------------
hyperparameter_grid:
  learning_rate:
    type: float
    log: true
    low: 0.0001
    high: 0.01

  n_layers:
    type: int
    low: 2
    high: 6

  d_token:                # multiples of 32 ensure divisibility by 4 & 8 heads
    type: categorical
    choices: [64, 96, 128, 160, 192, 224, 256]

  n_heads:
    type: categorical
    choices: [4, 8]

  d_ffn_factor:
    type: float
    low: 1.0
    high: 4.0

  attention_dropout:
    type: float
    low: 0.0
    high: 0.3

  ffn_dropout:
    type: float
    low: 0.0
    high: 0.3

  residual_dropout:
    type: float
    low: 0.0
    high: 0.3

  batch_size:
    type: categorical
    choices: [16, 32, 64]


# -------------------------- datasets ---------------------------
datasets:
  - dataset: B.204
    target: SOC_target
  - dataset: B.204
    target: pH_target
  - dataset: B.204
    target: Clay_target
  - dataset: BB.250
    target: SOC_target
  - dataset: BB.250
    target: pH_target
  - dataset: BB.250
    target: Clay_target
  - dataset: BB.51
    target: SOC_target
  - dataset: BB.51
    target: pH_target
  - dataset: BB.51
    target: Clay_target
  - dataset: BB.72
    target: SOC_target
  - dataset: BB.72
    target: pH_target
  - dataset: BB.72
    target: Clay_target
  - dataset: G.104
    target: SOC_target
  - dataset: G.104
    target: pH_target
  - dataset: G.104
    target: Clay_target
  - dataset: G.150
    target: SOC_target
  - dataset: G.150
    target: pH_target
  - dataset: G.150
    target: Clay_target
  - dataset: MG.112
    target: SOC_target
  - dataset: MG.112
    target: pH_target
  - dataset: MG.112
    target: Clay_target
  - dataset: MGS.101
    target: SOC_target
  - dataset: MGS.101
    target: pH_target
  - dataset: MGS.101
    target: Clay_target
  - dataset: NSW.52
    target: SOC_target
  - dataset: NSW.52
    target: pH_target
  - dataset: NSW.52
    target: Clay_target

# ------------------- optimisation / CV setup -------------------
optimization:
  n_trials: 100
  sampler: TPE
  sampler_params:
    n_startup_trials: 20
  cv:
    outer_folds: 5
    inner_folds: 5

# -------------- outer-fold training strategies -----------------
outer_train_strategies:
  agg_epochs_mean:
    enabled: true
  agg_epochs_mean_std:
    enabled: true
  agg_epochs_percentile:
    enabled: true
    percentile: 90
  best_inner_model:
    enabled: true
  full_train:
    enabled: true
    epochs: 256          # train full 256 epochs w/o early stopping
  early_stopping:
    enabled: true
    val_frac: 0.2
  ensemble:
    enabled: true