model: ft_transformer.FTTransformerRegressor
random_state: 42
results_dir: results/limesoda_fttransformer_optimize

fixed_parameters:
  use_fp16: false
  epochs: 1000
  use_early_stopping: true
  early_stopping_rounds: 40
  device: cuda
  random_state: 42
  use_pca: false
  n_pca_components: null
  feature_scaling: robust
  standardize_targets: true

hyperparameter_grid:
  learning_rate:
    type: float
    log: true
    low: 0.0001
    high: 0.01
  n_layers:
    type: int
    low: 1
    high: 4
  d_token:
    type: categorical
    choices: [16, 32, 48, 64]
  n_heads:
    type: categorical
    choices: [2, 4]
  d_ffn_factor:
    type: float
    low: 1.0
    high: 4.0
  attention_dropout:
    type: float
    low: 0.0
    high: 0.3
  ffn_dropout:
    type: float
    low: 0.0
    high: 0.3
  residual_dropout:
    type: float
    low: 0.0
    high: 0.3
  batch_size:
    type: categorical
    choices: [4, 8, 16, 32]

datasets:
  - dataset: B.204
    target: SOC_target
  - dataset: B.204
    target: pH_target
  - dataset: B.204
    target: Clay_target
  - dataset: BB.250
    target: SOC_target
  - dataset: BB.250
    target: pH_target
  - dataset: BB.250
    target: Clay_target
  - dataset: BB.30_1
    target: SOC_target
  - dataset: BB.30_1
    target: pH_target
  - dataset: BB.30_1
    target: Clay_target
  - dataset: BB.30_2
    target: SOC_target
  - dataset: BB.30_2
    target: pH_target
  - dataset: BB.30_2
    target: Clay_target
  - dataset: BB.51
    target: SOC_target
  - dataset: BB.51
    target: pH_target
  - dataset: BB.51
    target: Clay_target
  - dataset: BB.72
    target: SOC_target
  - dataset: BB.72
    target: pH_target
  - dataset: BB.72
    target: Clay_target
  - dataset: G.104
    target: SOC_target
  - dataset: G.104
    target: pH_target
  - dataset: G.104
    target: Clay_target
  - dataset: G.150
    target: SOC_target
  - dataset: G.150
    target: pH_target
  - dataset: G.150
    target: Clay_target
  - dataset: MG.112
    target: SOC_target
  - dataset: MG.112
    target: pH_target
  - dataset: MG.112
    target: Clay_target
  - dataset: MGS.101
    target: SOC_target
  - dataset: MGS.101
    target: pH_target
  - dataset: MGS.101
    target: Clay_target
  - dataset: MWP.36
    target: SOC_target
  - dataset: MWP.36
    target: pH_target
  - dataset: MWP.36
    target: Clay_target
  - dataset: NSW.52
    target: SOC_target
  - dataset: NSW.52
    target: pH_target
  - dataset: NSW.52
    target: Clay_target
  - dataset: PC.45
    target: SOC_target
  - dataset: PC.45
    target: pH_target
  - dataset: PC.45
    target: Clay_target
  - dataset: SC.50
    target: SOC_target
  - dataset: SC.50
    target: pH_target
  - dataset: SC.50
    target: Clay_target
  - dataset: SM.40
    target: SOC_target
  - dataset: SM.40
    target: pH_target
  - dataset: SM.40
    target: Clay_target
  - dataset: W.50
    target: SOC_target
  - dataset: W.50
    target: pH_target
  - dataset: W.50
    target: Clay_target

optimization:
  n_trials: 100
  sampler: TPE
  sampler_params:
    n_startup_trials: 20
    multivariate: true
  cv:
    outer_folds: 5
    inner_folds: 5

outer_train_strategies:
  agg_epochs_mean:
    enabled: true
  agg_epochs_mean_std:
    enabled: true
  agg_epochs_percentile:
    enabled: true
    percentile: 90
  best_inner_model:
    enabled: true
  full_train:
    enabled: true
    epochs: 256
  early_stopping:
    enabled: true
    val_frac: 0.2
  ensemble:
    enabled: true
