model: xgboost.XGBRegressor
random_state: 42
results_dir: results/limesoda_xgboost_optimize

fixed_parameters:
  epochs: 1000
  use_early_stopping: true
  early_stopping_rounds: 40
  use_pca: false
  n_pca_components: null
  random_state: 42
  n_jobs: -1

hyperparameter_grid:
  learning_rate:
    type: float
    log: true
    low: 0.001
    high: 0.3
  max_depth:
    type: int
    low: 3
    high: 10
  min_child_weight:
    type: int
    low: 1
    high: 10
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample_bytree:
    type: float
    low: 0.5
    high: 1.0
  gamma:
    type: float
    low: 0
    high: 5
  reg_alpha:
    type: float
    log: true
    low: 0.000001
    high: 10.0
  reg_lambda:
    type: float
    log: true
    low: 0.1
    high: 10.0

datasets:
  - dataset: B.204
    target: SOC_target
  - dataset: B.204
    target: pH_target
  - dataset: B.204
    target: Clay_target
  - dataset: BB.250
    target: SOC_target
  - dataset: BB.250
    target: pH_target
  - dataset: BB.250
    target: Clay_target
  - dataset: BB.51
    target: SOC_target
  - dataset: BB.51
    target: pH_target
  - dataset: BB.51
    target: Clay_target
  - dataset: BB.72
    target: SOC_target
  - dataset: BB.72
    target: pH_target
  - dataset: BB.72
    target: Clay_target
  - dataset: G.104
    target: SOC_target
  - dataset: G.104
    target: pH_target
  - dataset: G.104
    target: Clay_target
  - dataset: G.150
    target: SOC_target
  - dataset: G.150
    target: pH_target
  - dataset: G.150
    target: Clay_target
  - dataset: MG.112
    target: SOC_target
  - dataset: MG.112
    target: pH_target
  - dataset: MG.112
    target: Clay_target
  - dataset: MGS.101
    target: SOC_target
  - dataset: MGS.101
    target: pH_target
  - dataset: MGS.101
    target: Clay_target
  - dataset: NSW.52
    target: SOC_target
  - dataset: NSW.52
    target: pH_target
  - dataset: NSW.52
    target: Clay_target

optimization:
  n_trials: 100
  sampler: TPE
  sampler_params:
    n_startup_trials: 20
  cv:
    outer_folds: 5
    inner_folds: 5

outer_train_strategies:
  agg_epochs_mean:
    enabled: true
  agg_epochs_mean_std:
    enabled: true
  agg_epochs_percentile:
    enabled: true
  best_inner_model:
    enabled: true
  full_train:
    enabled: true
    epochs: 1000
  early_stopping:
    enabled: true
    val_frac: 0.2
  ensemble:
    enabled: true
