model: tabpfn.TabPFNRegressor
random_state: 42
results_dir: results/limesoda_tabpfn_optimize

fixed_parameters:
  n_estimators: 32
  device: cuda
  random_state: 42
  use_pca: false
  n_pca_components: null
  feature_scaling: null
  standardize_targets: null

datasets:
  - dataset: B.204
    target: SOC_target
  - dataset: B.204
    target: pH_target
  - dataset: B.204
    target: Clay_target
  - dataset: BB.250
    target: SOC_target
  - dataset: BB.250
    target: pH_target
  - dataset: BB.250
    target: Clay_target
  - dataset: BB.51
    target: SOC_target
  - dataset: BB.51
    target: pH_target
  - dataset: BB.51
    target: Clay_target
  - dataset: BB.72
    target: SOC_target
  - dataset: BB.72
    target: pH_target
  - dataset: BB.72
    target: Clay_target
  - dataset: G.104
    target: SOC_target
  - dataset: G.104
    target: pH_target
  - dataset: G.104
    target: Clay_target
  - dataset: G.150
    target: SOC_target
  - dataset: G.150
    target: pH_target
  - dataset: G.150
    target: Clay_target
  - dataset: MG.112
    target: SOC_target
  - dataset: MG.112
    target: pH_target
  - dataset: MG.112
    target: Clay_target
  - dataset: MGS.101
    target: SOC_target
  - dataset: MGS.101
    target: pH_target
  - dataset: MGS.101
    target: Clay_target
  - dataset: NSW.52
    target: SOC_target
  - dataset: NSW.52
    target: pH_target
  - dataset: NSW.52
    target: Clay_target

optimization:
  n_trials: 0
  sampler: TPE
  sampler_params:
    n_startup_trials: 20
  cv:
    outer_folds: 5
    inner_folds: 5

outer_train_strategies:
  agg_epochs_mean: 
    enabled: false
  agg_epochs_mean_std: 
    enabled: false
  agg_epochs_percentile: 
    enabled: false
  best_inner_model: 
    enabled: true
  full_train: 
    enabled: true
    epochs: 32
  early_stopping: 
    enabled: false
  ensemble: 
    enabled: true
