model: tabr.TabRRegressor
random_state: 42
results_dir: results/limesoda_ss_pca_tabr_optimize

fixed_parameters:
  use_fp16: false
  epochs: 1000
  use_early_stopping: true
  early_stopping_rounds: 40
  device: cuda
  random_state: 42
  use_pca: true
  n_pca_components: null
  feature_scaling: robust
  standardize_targets: true
  use_embeddings: false
  embedding_type: null
  embedding_dim: null

hyperparameter_grid:
  n_pca_components:
    type: int
    low: 2
    high: 32
  learning_rate:
    type: float
    log: true
    low: 0.0001
    high: 0.01
  d_main:
    type: categorical
    choices: [64, 128, 256, 512]
  d_multiplier:
    type: float
    low: 1.5
    high: 4.0
  encoder_n_blocks:
    type: int
    low: 0
    high: 4
  predictor_n_blocks:
    type: int
    low: 1
    high: 4
  dropout0:
    type: float
    low: 0.0
    high: 0.3
  context_dropout:
    type: float
    low: 0.0
    high: 0.3
  batch_size:
    type: categorical
    choices: [4, 8, 16, 32]

datasets:
  - dataset: CV.98
    target: SOC_target
  - dataset: CV.98
    target: pH_target
  - dataset: CV.98
    target: Clay_target
  - dataset: H.138
    target: SOC_target
  - dataset: H.138
    target: pH_target
  - dataset: H.138
    target: Clay_target
  - dataset: MG.44
    target: SOC_target
  - dataset: MG.44
    target: pH_target
  - dataset: MG.44
    target: Clay_target
  - dataset: NRW.115
    target: SOC_target
  - dataset: NRW.115
    target: pH_target
  - dataset: NRW.115
    target: Clay_target
  - dataset: NRW.42
    target: SOC_target
  - dataset: NRW.42
    target: pH_target
  - dataset: NRW.42
    target: Clay_target
  - dataset: NRW.62
    target: SOC_target
  - dataset: NRW.62
    target: pH_target
  - dataset: NRW.62
    target: Clay_target
  - dataset: O.32
    target: SOC_target
  - dataset: O.32
    target: pH_target
  - dataset: O.32
    target: Clay_target
  - dataset: SC.93
    target: SOC_target
  - dataset: SC.93
    target: pH_target
  - dataset: SC.93
    target: Clay_target
  - dataset: SL.125
    target: SOM_target
  - dataset: SL.125
    target: pH_target
  - dataset: SL.125
    target: Clay_target
  - dataset: SP.231
    target: SOM_target
  - dataset: SP.231
    target: pH_target
  - dataset: SP.231
    target: Clay_target
  - dataset: SSP.460
    target: SOC_target
  - dataset: SSP.460
    target: pH_target
  - dataset: SSP.460
    target: Clay_target
  - dataset: SSP.58
    target: SOC_target
  - dataset: SSP.58
    target: pH_target
  - dataset: SSP.58
    target: Clay_target
  - dataset: UL.120
    target: SOM_target
  - dataset: UL.120
    target: pH_target
  - dataset: UL.120
    target: Clay_target
  - dataset: RP.62
    target: SOC_target
  - dataset: RP.62
    target: pH_target
  - dataset: RP.62
    target: Clay_target
  - dataset: SA.112
    target: SOC_target
  - dataset: SA.112
    target: pH_target
  - dataset: SA.112
    target: Clay_target

optimization:
  n_trials: 100
  sampler: TPE
  sampler_params:
    n_startup_trials: 20
    multivariate: true
  cv:
    outer_folds: 5
    inner_folds: 5

outer_train_strategies:
  agg_epochs_mean:
    enabled: true
  agg_epochs_mean_std:
    enabled: true
  agg_epochs_percentile:
    enabled: true
    percentile: 90
  best_inner_model:
    enabled: true
  full_train:
    enabled: true
    epochs: 256
  early_stopping:
    enabled: true
    val_frac: 0.2
  ensemble:
    enabled: true
