model: rf.RandomForestRegressor
random_state: 42
results_dir: results/limesoda_ss_rf_optimize

fixed_parameters:
  n_estimators: 1000
  bootstrap: true
  criterion: squared_error
  random_state: 42
  n_jobs: -1
  use_pca: false
  n_pca_components: null
  feature_scaling: null
  standardize_targets: false

hyperparameter_grid:
  max_depth:
    type: int
    low: 3
    high: 30
  min_samples_split:
    type: int
    low: 2
    high: 10
  min_samples_leaf:
    type: int
    low: 1
    high: 10
  max_features:
    type: float
    low: 0.6
    high: 1.0

datasets:
  - dataset: CV.98
    target: SOC_target
  - dataset: CV.98
    target: pH_target
  - dataset: CV.98
    target: Clay_target
  - dataset: H.138
    target: SOC_target
  - dataset: H.138
    target: pH_target
  - dataset: H.138
    target: Clay_target
  - dataset: MG.44
    target: SOC_target
  - dataset: MG.44
    target: pH_target
  - dataset: MG.44
    target: Clay_target
  - dataset: NRW.115
    target: SOC_target
  - dataset: NRW.115
    target: pH_target
  - dataset: NRW.115
    target: Clay_target
  - dataset: NRW.42
    target: SOC_target
  - dataset: NRW.42
    target: pH_target
  - dataset: NRW.42
    target: Clay_target
  - dataset: NRW.62
    target: SOC_target
  - dataset: NRW.62
    target: pH_target
  - dataset: NRW.62
    target: Clay_target
  - dataset: O.32
    target: SOC_target
  - dataset: O.32
    target: pH_target
  - dataset: O.32
    target: Clay_target
  - dataset: SC.93
    target: SOC_target
  - dataset: SC.93
    target: pH_target
  - dataset: SC.93
    target: Clay_target
  - dataset: SL.125
    target: SOM_target
  - dataset: SL.125
    target: pH_target
  - dataset: SL.125
    target: Clay_target
  - dataset: SP.231
    target: SOM_target
  - dataset: SP.231
    target: pH_target
  - dataset: SP.231
    target: Clay_target
  - dataset: SSP.460
    target: SOC_target
  - dataset: SSP.460
    target: pH_target
  - dataset: SSP.460
    target: Clay_target
  - dataset: SSP.58
    target: SOC_target
  - dataset: SSP.58
    target: pH_target
  - dataset: SSP.58
    target: Clay_target
  - dataset: UL.120
    target: SOM_target
  - dataset: UL.120
    target: pH_target
  - dataset: UL.120
    target: Clay_target
  - dataset: RP.62
    target: SOC_target
  - dataset: RP.62
    target: pH_target
  - dataset: RP.62
    target: Clay_target
  - dataset: SA.112
    target: SOC_target
  - dataset: SA.112
    target: pH_target
  - dataset: SA.112
    target: Clay_target

optimization:
  n_trials: 100
  sampler: TPE
  sampler_params:
    n_startup_trials: 20
    multivariate: true
  cv:
    outer_folds: 5
    inner_folds: 5

outer_train_strategies:
  agg_epochs_mean:
    enabled: false
  agg_epochs_mean_std:
    enabled: false
  agg_epochs_percentile:
    enabled: false
  best_inner_model:
    enabled: true
  full_train:
    enabled: true
    epochs: 1000
  early_stopping:
    enabled: false
  ensemble:
    enabled: true
